# Generated by Django 4.2 on 2023-05-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cred',
        ),
    ]
