# Generated by Django 4.2 on 2023-05-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cred',
        ),
    ]
