# Generated by Django 4.2 on 2023-05-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cred',
        ),
    ]
